config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'techniques#index'
  resources :techniques do
    get :search, on: :collection
    resource :completes, only: [:create, :destroy]
  end
  resources :meetings, only: [:new,:create, :destroy]
  resources :users, only: [:show]
  resources :posts, only: [:show,:create, :destroy] do
    resources :comments, only: [:create, :destroy]
  end
  resources :comments, only: [:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post

  validates :content, presence: true

end

app/models/complete.rb
class Complete < ApplicationRecord
    belongs_to :user, optional: true
    belongs_to :technique, optional: true
end

app/models/meeting.rb
class Meeting < ApplicationRecord
  belongs_to :user

  with_options presence: true do
    validates :name
    validates :start_time
  end
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :comments, dependent: :destroy

  validates :content, presence: true
end

app/models/priority.rb
class Priority < ActiveHash::Base
  self.data = [
    { id: 1, name: '1' },
    { id: 2, name: '2' },
    { id: 3, name: '3' }
  ]

  include ActiveHash::Associations
  has_many :techniques
end

app/models/technique.rb
class Technique < ApplicationRecord
  belongs_to :user
  has_many    :completes, dependent: :destroy
  mount_uploader :video, VideoUploader

  with_options presence: true do
    validates :title
    validates :priority_id
    validates :description
    validates :target_on
    validates :completed_on
    validates :video
  end
  validate :start_finish_check
  validate :start_check

  def start_finish_check
    errors.add(:completed_on) if self.target_on > self.completed_on
  end

  def start_check
    errors.add(:target_on) if self.target_on < Time.now
  end
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :priority

  def completed_by?(user)
    completes.where(user_id: user.id).exists?
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :techniques, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :posts, dependent: :destroy
  has_many :completes, dependent: :destroy
  has_many :complete_techniques, through: :completes, source: :technique
  has_many :meetings
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :ward

  with_options presence: true do
    validates :name
    validates :nursing_history
    validates :ward_id
  end

  def posts
    return Post.where(user_id: self.id)
  end
end

app/models/ward.rb
class Ward < ActiveHash::Base
  self.data = [
    { id: 1, name: '北7階病棟' },
    { id: 2, name: '南7階病棟' },
    { id: 3, name: '北8階病棟' },
    { id: 4, name: '南8階病棟' },
    { id: 5, name: '北9階病棟' },
    { id: 6, name: '南9階病棟' }
  ]

  include ActiveHash::Associations
  has_many :users
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :authenticate_user!
  before_action :search_technique


  private
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name,:nursing_history,:ward_id])
  end

  def search_technique
    @search = Technique.ransack(params[:q])
    @techniques = @search.result
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def create
    @comment = Comment.new(comments_params)
    @comment.user_id = current_user.id
    if @comment.save
      redirect_back(fallback_location: root_path)
    else
      @post = @comment.post
      @comments = @post.comments
      render "posts/show"
    end
  end

  def destroy
    @comment = Comment.find(params[:id])
    if current_user.id = @comment.user_id
      @comment.destroy
      redirect_back(fallback_location: root_path)
    else
      render :show
    end
  end

  private
  def comments_params
    params.require(:comment).permit(:content).merge(user_id: current_user.id, post_id: params[:post_id])
  end

end

app/controllers/completes_controller.rb
class CompletesController < ApplicationController
  def create
    complete = current_user.completes.build(technique_id: params[:technique_id])
    complete.save
    redirect_back(fallback_location: root_path)
  end

  def destroy
    complete = Complete.find_by(technique_id: params[:technique_id], user_id: current_user.id)
    complete.destroy
    redirect_back(fallback_location: root_path)
  end
end

app/controllers/meetings_controller.rb
class MeetingsController < ApplicationController

  def new
    @meeting = Meeting.new
  end

  def create
    @meeting = Meeting.new(meeting_params)
    respond_to do |format|
      if @meeting.save
        format.html { redirect_to root_path, notice: 'Meeting was successfully created.' }
        format.json { render :show, status: :created, location: @meeting }
      else
        format.html { render :new }
        format.json { render json: @meeting.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @meeting = Meeting.find(params[:id])
    if current_user.id = @meeting.user_id
      @meeting.destroy
      redirect_back(fallback_location: root_path)
    else
      render :show
    end
  end

  private
    def meeting_params
      params.require(:meeting).permit(:name, :start_time).merge(user_id: current_user.id)
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def show
    @post = Post.find(params[:id])
    @comment = Comment.new
    @comments = @post.comments.includes(:user)
  end

  def create
    @post = Post.new(post_params)
    @post.user_id = current_user.id
    if @post.save
      redirect_back(fallback_location: root_path)
    else
      redirect_back(fallback_location: root_path)
    end
  end

  def destroy
    @post = Post.find(params[:id])
    if current_user.id = @post.user_id
      @post.destroy
      redirect_to root_path
    else
      render :show
    end
  end

  private
  def post_params
    params.require(:post).permit(:content).merge(user_id: current_user.id)
  end
end

app/controllers/techniques_controller.rb
class TechniquesController < ApplicationController
  def index
    @users = User.where("nursing_history <=3")
    @techniques = Technique.all.order('priority_id DESC')
    @techniques = @search.result
    @meetings = Meeting.all
  end

  def new
    @technique = Technique.new
  end

  def create
    @technique = Technique.new(techniques_params)
    if @technique.save
      redirect_to root_path
    else
      render :new
    end
  end

  def show
    @technique = Technique.find(params[:id])
  end

  def edit
    @technique = Technique.find(params[:id])
    unless current_user.nursing_history >= 4
      redirect_to root_path
    end
  end

  def update
    @technique = Technique.find(params[:id])
    respond_to do |format|
      if @technique.update(techniques_params) && @technique.video.recreate_versions!
        format.html { redirect_to @technique, notice: 'Article was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @technique.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @technique = Technique.find(params[:id])
    if current_user.nursing_history >= 4
      @technique.destroy
      redirect_to root_path
    else
      render :show
    end
  end

  private

  def techniques_params
    params.require(:technique).permit(:title, :priority_id, :description, :target_on, :completed_on, :video).merge(user_id: current_user.id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @Techniques = Technique.all
    @user = User.find(params[:id])
    @techniques = @user.techniques
    @complete_techniques = @user.completes.map{|complete| complete.technique}
    @post = Post.new
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/completes_helper.rb
module CompletesHelper
end

app/helpers/meetings_helper.rb
module MeetingsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/techniques_helper.rb
module TechniquesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/edit.html.erb
<div class="main users-edit">
  <div class="container">
    <div class="form-heading">コメント編集</div>
    <div class="form users-form">
      <div class="form-body">
        <%= form_with model: @comment,local: true do |f| %>
          <%= f.text_area :content %>
          <%= f.submit "編集する" %>
          <p><%=link_to 'もどる', user_path, class:"back-btn" %></p>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/meetings/new.html.erb
<%= render "shared/header" %>

<div class="main">
  <h2 class="title-sub">＜新規予定＞</h2>
  <%= form_with(model: @meeting, local: true) do |form| %>
    <% if @meeting.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@meeting.errors.count, "error") %> prohibited this meeting from being saved:</h2>
        <ul>
          <% @meeting.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
    <div class="new-plan">
      <h3 class="title-usa">予定
        <%= form.text_field :name %>
      </h3>

      <h3 class="title-usa">予定時刻
        <%= form.datetime_select :start_time %>
      </h3>
      <div class="actions">
        <%= form.submit "予定を追加する"%>
        <%= link_to 'トップへ戻る', root_path %>
      </div>
    </div>
  <% end %>
</div>
<%= render "shared/footer" %>

app/views/posts/show.html.erb
<%= render "shared/header" %>
<div class="main">
  <div class="comment-box">
    <h2 class='title-user'>＜質問情報＞</h2>
    <div class="user-example1">
      <p>質問者：<%= @post.user.name %></p>
      <p>テーマ：<%= @post.content %></p>
      <% if user_signed_in? && current_user.id == @post.user_id %>
        <%= link_to '削除', post_path(@post.id), method: :delete, class:'post-destroy' %>
      <% end %>
    </div>
    <div class="comments-box">
      <%= form_with model: [@post,@comment], local: true, method: :post do |f| %>
        <%= f.text_area :content %>
        <p><%= f.submit 'コメントする' %></p>
      <% end %>
      <div class='comments'>
        <% @comments.each do |comment| %>
          <p><%= comment.content %><%= comment.user.name %></p>
          <% if user_signed_in? && current_user.id == comment.user_id %>
            <%= link_to '削除', comment_path(comment.id), method: :delete, class:'comment-destroy' %><hr>
          <% end %>
        <% end %>
      </div>
    </div>
    <%= link_to "トップへ戻る", root_path %>
  </div>
</div>
<%= render "shared/footer" %>

app/views/techniques/edit.html.erb
<%= render "shared/header" %>
<div class="main">
  <h2 class="title-sub">＜技術の情報を入力＞</h2>
  <div class="techniques-main">
    <%= form_with model: @technique,local: true do |f| %>
      <%= render 'shared/error_messages', model: f.object %>
      <div class="new-techniques">
        <h3 class="title-usa">看護技術</h3>
        <%= f.text_area :title, class:"techniques-text", placeholder:"技術名（必須 40文字まで)", maxlength:"40" %>
        <div class="techniques-explain">
          <h3 class="title-usa">技術の説明</h3>
          <%= f.text_area :description, class:"techniques-text", placeholder:"技術の説明" ,rows:"7" ,maxlength:"1000" %>
        </div>
        <h3 class="manual">マニュアル
          <%= f.file_field :video, :accept => 'video/*' %>
        </h3>
        <h3 class="title-usa">優先度
          <%= f.collection_select(:priority_id, Priority.all, :id, :name, {}, {class:"select-box", id:"technique-priority"}) %>
        </h3>
        <h3 class="title-usa" for="">技術習得予定日
          <%= f.date_select :target_on, {}, class: 'form-control' %><br>
        </h3>
        <h3 class="title-usa" for="">技術習得締め日
          <%= f.date_select :completed_on, {}, class: 'form-control' %>
        </h3>
        <% if user_signed_in? && current_user.nursing_history >= 4 %>
          <%= f.submit "変更する" ,class:"technique-btn" %>
        <% end %>
        <%=link_to 'トップへもどる', root_path, class:"back-btn" %>
      </div>
    <% end %>
  </div>
</div>
<%= render "shared/footer" %>

app/views/techniques/index.html.erb
<%= render "shared/header" %>
<div class='main'>
  <div class="plans">
    <h2 class='title-sub'>＜予定一覧＞</h2>
    <%= week_calendar events: @meetings do |date,meetings| %>
      <%= date %>
      <% meetings.each do |meeting| %>
        <div>
          <%= meeting.name %>
          <%= link_to '削除', meeting_path(meeting.id), method: :delete, class:'meeting-destroy' %>
        </div>
      <% end %>
    <% end %>
  </div>

  <div class="category">
    <div class='rookies'>
      <h2 class='title-sub'>＜新人看護師＞</h2>
      <ul class='rookie-lists'>
        <% @users.each do |user| %>
          <li class='list'>
            <%= link_to user_path(user.id) do %>
              <div class='rookie-info'>
                <h3 class='rookie-name'>
                  <%= user.name %>
                </h3>
              </div>
            <% end %>
          </li>
        <% end %>
      </ul>
    </div>

    <div class='techniques'>
      <h2 class='title-sub'>＜技術項目＞</h2>
      <ul class='technique-lists'>
        <% @techniques.each do |technique| %>
          <li class='list'>
            <%= link_to technique_path(technique.id) do %>
              <div class='technique-info'>
                <h3 class='technique-name'>
                  <%= technique.title %>
                </h3>
              </div>
            <% end %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>
<%= render "shared/footer" %>

app/views/techniques/new.html.erb
<%= render "shared/header" %>
<div class="main">
  <h2 class="title-sub">＜技術の情報を入力＞</h2>
  <div class="techniques-main">
    <%= form_with model: @technique,local: true do |f| %>
      <%= render 'shared/error_messages', model: f.object %>
      <div class="new-techniques">
        <h3 class="title-usa">看護技術</h3>
        <%= f.text_area :title, class:"techniques-text", placeholder:"技術名（必須 40文字まで)", maxlength:"40" %>
        <div class="techniques-explain">
          <h3 class="title-usa">技術の説明</h3>
          <%= f.text_area :description, class:"techniques-text", placeholder:"技術の説明" ,rows:"7" ,maxlength:"1000" %>
        </div>
        <h3 class="manual">マニュアル
          <%= f.file_field :video, :accept => 'video/*' %>
        </h3>
        <h3 class="title-usa">優先度
          <%= f.collection_select(:priority_id, Priority.all, :id, :name, {}, {class:"select-box", id:"technique-priority"}) %>
        </h3>
        <h3 class="title-usa" for="">技術習得予定日
          <%= f.date_select :target_on, {}, class: 'form-control' %><br>
        </h3>
        <h3 class="title-usa" for="">技術習得締め日
          <%= f.date_select :completed_on, {}, class: 'form-control' %>
        </h3>
        <% if user_signed_in? && current_user.nursing_history >= 4 %>
          <%= f.submit "追加する" ,class:"technique-btn" %>
          <%=link_to 'トップへもどる', root_path, class:"back-btn" %>
        <% end %>
      </div>
    <% end %>
  </div>
</div>
<%= render "shared/footer" %>

app/views/techniques/show.html.erb
<%= render "shared/header" %>
<div class='main'>
  <div class='technique-box'>
    <h2 class='technique-name1'>
      <%= @technique.title %>
    </h2><hr>
    <div class='technique-image-content'>
      <%= link_to @technique.video_url.to_s do %>
        <%= image_tag(@technique.video_url(:screenshot).to_s, id: "video", :alt => "screenshot") %>
      <% end %>
    </div>
    <div class="technique-explain-box">
      <span><%= @technique.description %></span>
    </div>
    <div class="technique-example">
      <span>優先度：<%= @technique.priority.name %></span><br>
      <span>技術習得予定日：<%= @technique.target_on %></span>
      <span> 〜 <%= @technique.completed_on %></span>
    </div><br>
    <% if user_signed_in? && current_user.nursing_history >= 4 %>
      <%= link_to '編集', edit_technique_path(@technique.id), method: :get, class: "technique-red-btn" %>
      <%= link_to '削除', technique_path(@technique.id), method: :delete, class:'technique-destroy' %>
    <% end %>
    <%= link_to "トップへ戻る", root_path%>
  </div>
</div>
<%= render "shared/footer" %>

app/views/users/show.html.erb
<%= render "shared/header" %>
<div class="main">
  <div class="technique-user">
    <div class="Account__info">
      <h2 class='title-user'>＜新人情報＞</h2>
      <div class="user-example">
        <p>名前：<%= @user.name %></p>
        <p>看護師歴：<%= @user.nursing_history %>年</p>
        <p>病棟名：<%= @user.ward.name %></p>
      </div>
    </div>
    <div class="Technique＿info">
      <h2 class='title-user'>＜技術進捗＞</h2>
      <div class="user-example">
        <% @Techniques.each do |technique| %>
          <%= link_to technique.title, technique_path(technique.id), class: :card__title%>
          <% if technique.completed_by?(current_user) || technique.completes.present? %>
            <%=link_to "完了", technique_completes_path(technique.id), method: :delete %><br>
          <% else %>
            <%=link_to "未完了", technique_completes_path(technique.id), method: :post %><br>
          <% end %>
        <% end %>
      </div>
      <hr>
      <h2 class='title-user'>＜経験済み技術＞</h2>
      <div class="user-example">
        <% @complete_techniques.each do |technique| %>
          <p><%=link_to technique.title, technique_path(technique.id) %></p>
        <% end %>
      </div>
    </div><br>
  </div>
  <div class="Comment＿info">
    <div class="question">
      <h2 class='title-user'>＜質問・悩み＞</h2>
      <div class="user-example">
        <% @user.posts.each do |post| %>
          <p><%= link_to post.content, post_path(post.id), class: :card__title%></p>
        <% end %>
      </div>
    </div>
    <div class="question-form">
      <h2 class='title-user'>＜質問テーマ記入フォーム＞</h2>
      <% if user_signed_in? && current_user.id.to_s == params[:id] %>
        <div class="user-example">
          <%= form_for @post do |f| %>
            <%= f.text_field :content %>
            <%= f.submit '質問する' %>
          <% end %>
        </div>
      <% end %>
      <%= link_to "トップへ戻る", root_path%>
    </div>
  </div>
</div>
<%= render "shared/footer" %>