config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'techniques#index'
  resources :techniques do
    get :search, on: :collection
    resource :completes, only: [:create, :destroy]
  end
  resources :meetings, only: [:new,:create, :destroy]
  resources :users, only: [:show]
  resources :posts, only: [:show,:create, :destroy] do
    resources :comments, only: [:create, :destroy]
  end
  resources :comments, only: [:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post

  validates :content, presence: true

end

app/models/complete.rb
class Complete < ApplicationRecord
    belongs_to :user, optional: true
    belongs_to :technique, optional: true
end

app/models/meeting.rb
class Meeting < ApplicationRecord
  belongs_to :user

  with_options presence: true do
    validates :name
    validates :start_time
  end
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :comments, dependent: :destroy

  validates :content, presence: true
end

app/models/priority.rb
class Priority < ActiveHash::Base
  self.data = [
    { id: 1, name: '1' },
    { id: 2, name: '2' },
    { id: 3, name: '3' }
  ]

  include ActiveHash::Associations
  has_many :techniques
end

app/models/technique.rb
class Technique < ApplicationRecord
  belongs_to :user
  has_many    :completes, dependent: :destroy
  mount_uploader :video, VideoUploader

  with_options presence: true do
    validates :title
    validates :priority_id
    validates :description
    validates :target_on
    validates :completed_on
    validates :video
  end
  validate :start_finish_check
  validate :start_check

  def start_finish_check
    errors.add(:completed_on) if self.target_on > self.completed_on
  end

  def start_check
    errors.add(:target_on) if self.target_on < Time.now
  end
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :priority

  def completed_by?(user)
    completes.where(user_id: user.id).exists?
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :techniques, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :posts, dependent: :destroy
  has_many :completes, dependent: :destroy
  has_many :complete_techniques, through: :completes, source: :technique
  has_many :meetings
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :ward

  with_options presence: true do
    validates :name
    validates :nursing_history
    validates :ward_id
  end

  def posts
    return Post.where(user_id: self.id)
  end
end

app/models/ward.rb
class Ward < ActiveHash::Base
  self.data = [
    { id: 1, name: '北7階病棟' },
    { id: 2, name: '南7階病棟' },
    { id: 3, name: '北8階病棟' },
    { id: 4, name: '南8階病棟' },
    { id: 5, name: '北9階病棟' },
    { id: 6, name: '南9階病棟' }
  ]

  include ActiveHash::Associations
  has_many :users
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def create
    @comment = Comment.new(comments_params)
    @comment.user_id = current_user.id
    if @comment.save
      redirect_back(fallback_location: root_path)
    else
      @post = @comment.post
      @comments = @post.comments
      render "posts/show"
    end
  end

  def destroy
    @comment = Comment.find(params[:id])
    if current_user.id = @comment.user_id
      @comment.destroy
      redirect_back(fallback_location: root_path)
    else
      render :show
    end
  end

  private
  def comments_params
    params.require(:comment).permit(:content).merge(user_id: current_user.id, post_id: params[:post_id])
  end

end

app/controllers/meetings_controller.rb
class MeetingsController < ApplicationController

  def new
    @meeting = Meeting.new
  end

  def create
    @meeting = Meeting.new(meeting_params)
    respond_to do |format|
      if @meeting.save
        format.html { redirect_to root_path, notice: 'Meeting was successfully created.' }
        format.json { render :show, status: :created, location: @meeting }
      else
        format.html { render :new }
        format.json { render json: @meeting.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @meeting = Meeting.find(params[:id])
    if current_user.id = @meeting.user_id
      @meeting.destroy
      redirect_back(fallback_location: root_path)
    else
      render :show
    end
  end

  private
    def meeting_params
      params.require(:meeting).permit(:name, :start_time).merge(user_id: current_user.id)
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def show
    @post = Post.find(params[:id])
    @comment = Comment.new
    @comments = @post.comments.includes(:user)
  end

  def create
    @post = Post.new(post_params)
    @post.user_id = current_user.id
    if @post.save
      redirect_back(fallback_location: root_path)
    else
      redirect_back(fallback_location: root_path)
    end
  end

  def destroy
    @post = Post.find(params[:id])
    if current_user.id = @post.user_id
      @post.destroy
      redirect_to root_path
    else
      render :show
    end
  end

  private
  def post_params
    params.require(:post).permit(:content).merge(user_id: current_user.id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @Techniques = Technique.all
    @user = User.find(params[:id])
    @techniques = @user.techniques
    @complete_techniques = @user.completes.map{|complete| complete.technique}
    @post = Post.new
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/completes_helper.rb
module CompletesHelper
end

app/helpers/meetings_helper.rb
module MeetingsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/techniques_helper.rb
module TechniquesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Nurseapp32473</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if model.errors.any? %>
<div class="error-alert">
  <ul>
    <% model.errors.full_messages.each do |message| %>
    <li class='error-message'><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

app/views/shared/_footer.html.erb
<footer class= "top-page-footer">
  <h2 class= "title-sub">＜指導者入力フォーム＞</h2>
  <% if user_signed_in? && current_user.nursing_history >= 4 %>
      <%= link_to new_technique_path do %>
        <span class='btn-text'>技術を追加する</span>
      <% end %>
      <hr>
      <%= link_to new_meeting_path do %>
        <span class='btn-text'>予定を追加する</span>
      <% end %>
  <% end %>
</footer>

app/views/shared/_header.html.erb
<header class='top-page-header'>
  <h1 class='title-main'>新人教育チェックリスト</h1>
  <div class='left_header'>
    <div class="search-form">
      <%= search_form_for @search do |f| %>
        <%= f.search_field :title_cont, placeholder:'キーワードから探す'%>
        <%= f.collection_select(:priority_id_eq, Priority.all, :id, :name, {}, {class:"select-box"})%>優先度
        <%= f.submit :'検索', class:"search-button" %>
      <% end %>
    </div>
  </div>
  <div class='nav'>
    <ul class='list'>
      <% if user_signed_in? %>
        <li><%= link_to current_user.name, user_path(current_user), class: "user-name" %></li>
        <li><%= link_to 'ログアウト', destroy_user_session_path, method: :delete, class: "logout" %></li>
      <% end %>
    </ul>
  </div>
</header>

app/views/simple_calendar/_week_calendar.html.erb
<div class="simple-calendar">
  <div class="calendar-heading">
    <%= link_to t('simple_calendar.previous', default: '先週'), calendar.url_for_previous_view %>
    <% if calendar.number_of_weeks == 1 %>
      <span class="calendar-title"> <%= calendar.week_number %>週目</span>
    <%else%>
        <span class="calendar-title"> <%= calendar.week_number %> 週目 <%= calendar.end_week %></span>
    <%end%>
        <%= link_to t('simple_calendar.next', default: '来週'), calendar.url_for_next_view %>
  </div>

  <table class="table table-striped">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <tr>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(passed_block) %>
                <% capture_haml(day, sorted_events.fetch(day, []), &passed_block) %>
              <% else %>
                <% passed_block.call day, sorted_events.fetch(day, []) %>
              <% end %>
            <% end %>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>